# Change these first
owner: Lyra-Core # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  # Backend APIs
  - name: Backend APIs
    url: https://api.lyrawellbeing.health/status-0123456789abcdef
    maxResponseTime: 3000  

# Main sites
  - name: TestShouldFail
    url: https://app222.lyrawellbeing.health
    maxResponseTime: 3000

  # Main sites
  - name: Hub
    url: https://app.lyrawellbeing.health
    maxResponseTime: 3000

  - name: Portal
    url: https://portal.lyrawellbeing.health
    maxResponseTime: 3000

  # Chat Platforms
  - name: Schweiz Chat
    url: https://lyrawellbeing.help/
    maxResponseTime: 3000
    
  - name: Zoho
    url: https://salesiq.zoho.eu/icas/liveview
    maxResponseTime: 10000

  # Additional International Domains
  - name: Argentina Website
    url: https://lyrawellbeing.ar
    maxResponseTime: 3000

  - name: Austria Website
    url: https://lyrawellbeing.at
    maxResponseTime: 3000

  - name: Belgium Website
    url: https://lyra-wellbeing.be/
    maxResponseTime: 3000

  - name: Canada Website
    url: https://lyrawellbeing.ca
    maxResponseTime: 3000

  - name: France Website
    url: https://lyrawellbeing.fr
    maxResponseTime: 3000

  - name: Germany Website
    url: https://lyrawellbeing.de
    maxResponseTime: 3000

  - name: Hungary Website
    url: https://lyrawellbeing.hu
    maxResponseTime: 3000

  - name: India Website
    url: https://lyrawellbeing.in
    maxResponseTime: 3000

  - name: International Website
    url: https://lyrahealthinternational.com
    maxResponseTime: 3000

  - name: Italy Website
    url: https://lyrawellbeing.it
    maxResponseTime: 3000

  - name: Kenya Website
    url: https://lyrawellbeing.co.ke
    maxResponseTime: 3000

  - name: Luxembourg Website
    url: https://lyrawellbeing.lu
    maxResponseTime: 3000

  - name: Malaysia Website
    url: https://lyrawellbeing.my
    maxResponseTime: 3000

  - name: Mexico Website
    url: https://lyrawellbeing.com.mx
    maxResponseTime: 3000

  - name: Netherlands Website
    url: https://lyrawellbeing.nl
    maxResponseTime: 3000

  - name: Portugal Website
    url: https://lyrawellbeing.pt
    maxResponseTime: 3000

  - name: Schweiz Website
    url: https://lyrawellbeing.ch
    maxResponseTime: 3000

  - name: Singapore Website
    url: https://lyrawellbeing.sg
    maxResponseTime: 3000

  - name: South Africa Website
    url: https://lyrawellbeing.co.za
    maxResponseTime: 3000

  - name: Spain Website
    url: https://lyrawellbeing.es
    maxResponseTime: 3000

  - name: United Arab Emirates Website
    url: https://lyrawellbeing.ae
    maxResponseTime: 3000

  - name: United Kingdom Website
    url: https://lyrawellbeing.uk
    maxResponseTime: 3000


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lyrawellbeing.health
  logoUrl: https://lyra-core.github.io/Status/lyra-logo.png
  favicon: https://lyra-core.github.io/Status/favicon.png
  themeUrl: https://lyra-core.github.io/Status/theme.css
  name: Lyra Wellbeing Status
  introTitle: "Lyra Wellbeing System Status"
  introMessage: "We continuously monitor the performance and availability of Lyra Wellbeing’s platform. This page provides real-time insights into our APIs, applications, and integrations—so you can stay focused on wellbeing, not uptime."
  metaTags:
    - name: description
      content: "Live uptime and performance monitoring for Lyra Wellbeing’s services and integrations."

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
