# Change these first
owner: Lyra-Core # Your GitHub organization or username, where this repository lives
repo: Status # The name of this repository

sites:
  # Backend APIs - Multi-region monitoring
  - name: Backend APIs
    url: https://api.lyrawellbeing.health/status-0123456789abcdef
    maxResponseTime: 3000  
  
  # Hub - Multi-region monitoring
  - name: Hub
    url: https://app.lyrawellbeing.health   
    maxResponseTime: 3000 
  
  # Portal - Multi-region monitoring
  - name: Portal
    url: https://portal.lyrawellbeing.health   
    maxResponseTime: 3000
   
  # Zoho - Single check (no regional monitoring)
  - name: Zoho
    url: https://salesiq.zoho.eu/icas/liveview
    maxResponseTime: 10000
  
  # International Website - Multi-region monitoring
  - name: International Website
    url: https://lyrahealthinternational.com
    maxResponseTime: 3000
  
  # Schweiz Website - Multi-region monitoring
  - name: Schweiz Website
    url: https://lyrawellbeing.ch
    maxResponseTime: 3000
  
  # Germany Website - Multi-region monitoring
  - name: Germany Website
    url: https://lyrawellbeing.de
    maxResponseTime: 3000
  
  # France Website - Multi-region monitoring
  - name: France Website
    url: https://lyrawellbeing.fr
    maxResponseTime: 3000
  
  # Help Website - Multi-region monitoring
  - name: Help Website
    url: https://lyrawellbeing.help
    maxResponseTime: 3000

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.lyrawellbeing.health
  baseUrl: /Status
  logoUrl: https://lyra-core.github.io/Status/lyra-logo.png
  favicon: https://lyra-core.github.io/Status/favicon.png
  themeUrl: https://lyra-core.github.io/Status/theme.css
  name: Lyra Wellbeing Status
  introTitle: "Lyra Wellbeing System Status"
  introMessage: "We continuously monitor the performance and availability of Lyra Wellbeing’s platform. This page provides real-time insights into our APIs, applications, and integrations—so you can stay focused on wellbeing, not uptime."
  metaTags:
    - name: description
      content: "Live uptime and performance monitoring for Lyra Wellbeing’s services and integrations."
  navbar:
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
